import React from 'react';
import { MarkdownRenderer } from './MarkdownRenderer';

interface SynthesisReportProps {
  content: string;
}

export const SynthesisReport: React.FC<SynthesisReportProps> = ({ content }) => {
  return (
    <div className="bg-slate-800 rounded-xl border border-slate-700 shadow-2xl overflow-hidden mt-8">
      <div className="bg-gradient-to-r from-blue-900 to-slate-900 p-6 border-b border-slate-700 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-blue-500/20 rounded-lg text-blue-400">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
            </svg>
          </div>
          <div>
            <h2 className="text-xl font-bold text-white">Strategic Investment Report</h2>
            <p className="text-sm text-blue-300">Synthesized Recommendation</p>
          </div>
        </div>
        <div className="hidden sm:block px-3 py-1 bg-blue-500/10 border border-blue-500/30 rounded-full text-xs text-blue-300 font-mono">
          MODEL: GEMINI-3-PRO
        </div>
      </div>
      
      <div className="p-8 bg-slate-800/50">
        <MarkdownRenderer content={content} />
      </div>
      
      <div className="bg-slate-900 p-4 text-center text-xs text-slate-500 border-t border-slate-700">
        Disclaimer: This analysis is generated by AI for informational purposes only and does not constitute financial advice.
      </div>
    </div>
  );
};
